-- usingcovidfinaltestdb


CREATE TABLE covid2 (
id INT PRIMARY KEY,
date DATE,
country VARCHAR(2),
state VARCHAR(2),
county VARCHAR(25),
fips INTEGER,
lat VARCHAR(10),
long VARCHAR(10),
locationId VARCHAR(100),
actuals_cases DEC(38,5),
actuals_deaths DEC(38,5),
actuals_positiveTests DEC(38,5),
actuals_negativeTests DEC(38,5),
actuals_contactTracers DEC(38,5),
actuals_hospitalBeds_capacity DEC(38,5),
actuals_hospitalBeds_currentUsageTotal DEC(38,5),
actuals_hospitalBeds_currentUsageCovid DEC(38,5),
actuals_hospitalBeds_typicalUsageRate DEC(38,5),
actuals_icuBeds_capacity DEC(38,5),
actuals_icuBeds_currentUsageTotal DEC(38,5),
actuals_icuBeds_currentUsageCovid DEC(38,5),
actuals_icuBeds_typicalUsageRate DEC(38,5),
actuals_newCases DEC(38,5),
actuals_vaccinesDistributed DEC(38,5),
actuals_vaccinationsInitiated DEC(38,5),
actuals_vaccinationsCompleted DEC(38,5),
metrics_testPositivityRatio DEC(38,5),
metrics_testPositivityRatioDetails DEC(38,5),
metrics_caseDensity DEC(38,5),
metrics_contactTracerCapacityRatio DEC(38,5),
metrics_infectionRate DEC(38,5),
metrics_infectionRateCI90 DEC(38,5),
metrics_icuHeadroomRatio DEC(38,5),
metrics_icuHeadroomDetails DEC(38,5),
metrics_icuCapacityRatio DEC(38,5),
riskLevels_overall VARCHAR(2),
metrics_vaccinationsInitiatedRatio DEC(38,5),
metrics_vaccinationsCompletedRatio DEC(38,5),
actuals_newDeaths DEC(38,5),
actuals_vaccinesAdministered DEC(38,5)
);
select * from covid2;