select count(*) from covid.covid_timeseries_2;
truncate table covid.covid_timeseries_1;
select * from covid.covid_timeseries_1;
create table covid.covid_timeseries_2
(
date_dt Date,
country VARCHAR(2),
state VARCHAR(2),
county VARCHAR(25),
fips INTEGER,
latitude VARCHAR(10),
longitude VARCHAR(10),
locationId VARCHAR(100),
actuals_cases Decimal(38,5),
actuals_deaths Decimal(38,5),
actuals_positiveTests Decimal(38,5),
actuals_negativeTests Decimal(38,5),
actuals_contactTracers Decimal(38,5),
actuals_hospitalBeds_capacity Decimal(38,5),
actuals_hospitalBeds_currentUsageTotal Decimal(38,5),
actuals_hospitalBeds_currentUsageCovid Decimal(38,5),
actuals_hospitalBeds_typicalUsageRate Decimal(38,5),
actuals_icuBeds_capacity Decimal(38,5),
actuals_icuBeds_currentUsageTotal Decimal(38,5),
actuals_icuBeds_currentUsageCovid Decimal(38,5),
actuals_icuBeds_typicalUsageRate Decimal(38,5),
actuals_newCases Decimal(38,5),
actuals_vaccinesDistributed Decimal(38,5),
actuals_vaccinationsInitiated Decimal(38,5),
actuals_vaccinationsCompleted Decimal(38,5),
metrics_testPositivityRatio Decimal(38,5),
metrics_testPositivityRatioDetails Decimal(38,5),
metrics_caseDensity Decimal(38,5),
metrics_contactTracerCapacityRatio Decimal(38,5),
metrics_infectionRate Decimal(38,5),
metrics_infectionRateCI90 Decimal(38,5),
metrics_icuHeadroomRatio Decimal(38,5),
metrics_icuHeadroomDetails Decimal(38,5),
metrics_icuCapacityRatio Decimal(38,5),
riskLevels_overall VARCHAR(2),
metrics_vaccinationsInitiatedRatio Decimal(38,5),
metrics_vaccinationsCompletedRatio Decimal(38,5),
actuals_newDeaths Decimal(38,5),
actuals_vaccinesAdministered Decimal(38,5),
primary key (state, date_dt)
	) ENGINE=InnoDB